In [2]:
import numpy as np

In [3]:
nums=np.arange(1,11)
nums

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
nums>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [6]:
nums[nums<5]

array([1, 2, 3, 4])

In [9]:
num=(nums>5) & (nums%2==0)
nums[num]

array([ 6,  8, 10])

# Arithmetic Operators

In [11]:
numbers=np.arange(1,21,2)
numbers

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [12]:
numbers*2

array([ 2,  6, 10, 14, 18, 22, 26, 30, 34, 38])

In [13]:
numbers/5

array([0.2, 0.6, 1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8])

In [14]:
numbers/numbers

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
numbers-2

array([-1,  1,  3,  5,  7,  9, 11, 13, 15, 17])

In [16]:
np.subtract(numbers,5)

array([-4, -2,  0,  2,  4,  6,  8, 10, 12, 14])

In [17]:
np.multiply(numbers,1.75)

array([ 1.75,  5.25,  8.75, 12.25, 15.75, 19.25, 22.75, 26.25, 29.75,
       33.25])

In [18]:
numbers**3

array([   1,   27,  125,  343,  729, 1331, 2197, 3375, 4913, 6859],
      dtype=int32)

In [19]:
np.power(numbers,2)

array([  1,   9,  25,  49,  81, 121, 169, 225, 289, 361], dtype=int32)

In [21]:
np.sqrt(numbers)

array([1.        , 1.73205081, 2.23606798, 2.64575131, 3.        ,
       3.31662479, 3.60555128, 3.87298335, 4.12310563, 4.35889894])

In [22]:
np.cos(180)

-0.5984600690578582

In [23]:
np.sin(numbers)

array([ 0.84147098,  0.14112001, -0.95892427,  0.6569866 ,  0.41211849,
       -0.99999021,  0.42016704,  0.65028784, -0.96139749,  0.14987721])

In [24]:
np.log(numbers)

array([0.        , 1.09861229, 1.60943791, 1.94591015, 2.19722458,
       2.39789527, 2.56494936, 2.7080502 , 2.83321334, 2.94443898])

# Statistical Operators

In [25]:
n1=np.arange(1,11)
n1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
np.sum(n1)

55

In [27]:
np.mean(n1)

5.5

In [28]:
np.median(n1)

5.5

In [32]:
np.min(n1)
np.max(n1)

10

In [33]:
np.std(n1)

2.8722813232690143

In [34]:
np.var(n1)

8.25

In [45]:
coef=np.array([[2,1],[-3,6]])
coef

array([[ 2,  1],
       [-3,  6]])

In [46]:
result=np.array([5,0])
result

array([5, 0])

In [47]:
np.linalg.solve(coef,result)

array([2., 1.])