In [3]:
l1=[1,3,5,7,9]
l2=[2,4,6,8,10]

In [5]:
l3=[]

for i in range(0,len(l1)):
    x=l1[i]*l2[i]
    l3.append(x)
    
print(l3)

[2, 12, 30, 56, 90]


In [6]:
import numpy as np

In [8]:
x=np.array([1,3,5,7,9])
y=np.array([2,4,6,8,10])

x*y

array([ 2, 12, 30, 56, 90])

In [ ]:
# NUMPY ARRAY

In [12]:
a=[2.5,3]
print(type(a))

<class 'list'>


In [18]:
np_a=np.array([2.5,3,6])
np_a

array([2.5, 3. , 6. ])

In [19]:
np_b=np.array([2.5,3,6],dtype='int')
np_b

array([2, 3, 6])

In [21]:
a=np.zeros(3)
a

array([0., 0., 0.])

In [24]:
b=np.zeros((2,3),dtype='int')
b

array([[0, 0, 0],
       [0, 0, 0]])

In [28]:
x=np.ones(5)
x

array([1., 1., 1., 1., 1.])

In [31]:
y=np.ones((3,4,5),dtype='int')
y

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [39]:
x=np.full(3,9)
x

array([9, 9, 9])

In [41]:
x=np.full((3,4),9,dtype='float')
x

array([[9., 9., 9., 9.],
       [9., 9., 9., 9.],
       [9., 9., 9., 9.]])

In [45]:
x=np.arange(1,6,1,dtype='int')
x

array([1, 2, 3, 4, 5])

In [48]:
x=np.eye(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
x=np.eye(3,2)
x

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [51]:
x=np.eye(2,3,dtype='bool')
x

array([[ True, False, False],
       [False,  True, False]])

In [52]:
x=np.linspace(10,20,num=15)
x

array([10.        , 10.71428571, 11.42857143, 12.14285714, 12.85714286,
       13.57142857, 14.28571429, 15.        , 15.71428571, 16.42857143,
       17.14285714, 17.85714286, 18.57142857, 19.28571429, 20.        ])

In [54]:
x=np.random.rand(10)
x

array([0.95117547, 0.76837261, 0.38242321, 0.36417973, 0.11605329,
       0.62469191, 0.49185922, 0.26447293, 0.36731089, 0.32388473])

In [57]:
x=np.random.rand(3,3)
x

array([[0.90038938, 0.61846688, 0.17061343],
       [0.08131779, 0.51132757, 0.39594735],
       [0.6011982 , 0.4805253 , 0.05882988]])

In [59]:
x=np.random.randn(2,4)
x

array([[ 0.3132342 , -0.02521688,  0.38884617,  0.12162739],
       [ 0.59869958,  2.32498816,  0.7646238 , -0.3381947 ]])

In [61]:
x=np.random.normal(10,5,(3,3))
x

array([[ 5.83431411,  4.61155097,  3.80394695],
       [ 8.87759075, 16.21024793, 13.25302854],
       [ 3.25391503,  3.44695843, 16.87788897]])

In [62]:
x=np.random.randint(0,5,(3,3))
x

array([[0, 3, 2],
       [2, 4, 3],
       [0, 0, 1]])

In [71]:
x=np.random.randint(0,25,(4,4))
x

print(np.ndim(x))
print(np.size(x))
print(x.dtype)

2
16
<class 'numpy.dtype'>
int32
